project:
  type: website

website:
  title: "Coverage Prediction"
  navbar:
    title: "Scholarship project"
    # style: "docked"
    background: "primary"
    foreground: "light"
    # search: true
    left:
      - href: index.qmd
        text: Introduction
      - href: cleaning.ipynb
        text: Data Cleaning
      - href: EDA.qmd
        text: EDA
      - text: "Analysis"
        menu:
          - href: Overview_Analysis.qmd
            text: Overview
          - href: Analysis_85.qmd
            text: RCP8.5
          - href: Analysis_45.qmd
            text: RCP4.5
      - href: Conclusion.qmd
        text: Furture Actions


bibliography: references.bib
csl: nature.csl

format:
  html:
    page-layout: full
    theme: cosmo
    toc: true


